name: Update gist with WakaTime stats

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update-gist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: waka-box
        uses: matchai/waka-box@v5.0.0
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 51b3b07c8ea7a62e1e3b14b0b01240ed
